CREATE TABLE user_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    skill_name VARCHAR(100) NOT NULL,

    proficiency VARCHAR(20) NOT NULL,

    years_of_experience NUMERIC(4,1),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_skills_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_user_skills_proficiency
        CHECK (
            proficiency IN (
                'BEGINNER',
                'INTERMEDIATE',
                'ADVANCED',
                'EXPERT'
            )
        ),

    CONSTRAINT chk_user_skills_experience
        CHECK (
            years_of_experience IS NULL
            OR years_of_experience >= 0
        ),

    CONSTRAINT uq_user_skills_user_skill
        UNIQUE (user_id, skill_name)
);
