CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    company_name VARCHAR(150) NOT NULL,
    job_title VARCHAR(150) NOT NULL,

    job_url VARCHAR(500),
    location VARCHAR(150),

    employment_type VARCHAR(30),

    application_status VARCHAR(30) NOT NULL DEFAULT 'APPLIED',

    applied_date DATE,
    deadline DATE,

    notes VARCHAR(2000),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_job_applications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_job_application_status
        CHECK (
            application_status IN (
                'WISHLIST',
                'APPLIED',
                'ASSESSMENT',
                'INTERVIEW',
                'OFFERED',
                'REJECTED',
                'WITHDRAWN'
            )
        ),

    CONSTRAINT chk_job_employment_type
        CHECK (
            employment_type IS NULL
            OR employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'INTERNSHIP',
                'CONTRACT',
                'FREELANCE'
            )
        ),

    CONSTRAINT chk_job_application_dates
        CHECK (
            deadline IS NULL
            OR applied_date IS NULL
            OR deadline >= applied_date
        )
);

CREATE INDEX idx_job_applications_user_id
    ON job_applications(user_id);

CREATE INDEX idx_job_applications_user_status
    ON job_applications(user_id, application_status);
