CREATE TABLE user_educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    institution_name VARCHAR(200) NOT NULL,
    degree VARCHAR(150) NOT NULL,
    field_of_study VARCHAR(150),

    start_date DATE NOT NULL,
    end_date DATE,

    currently_studying BOOLEAN NOT NULL DEFAULT FALSE,

    grade VARCHAR(50),
    description VARCHAR(1000),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_educations_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_education_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        ),

    CONSTRAINT chk_current_education_end_date
        CHECK (
            currently_studying = FALSE
            OR end_date IS NULL
        )
);

CREATE INDEX idx_user_educations_user_id
    ON user_educations(user_id);

CREATE INDEX idx_user_educations_user_start_date
    ON user_educations(user_id, start_date DESC);
