CREATE TABLE user_experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    company_name VARCHAR(200) NOT NULL,
    job_title VARCHAR(150) NOT NULL,
    employment_type VARCHAR(30) NOT NULL,

    location VARCHAR(150),

    start_date DATE NOT NULL,
    end_date DATE,

    currently_working BOOLEAN NOT NULL DEFAULT FALSE,

    description VARCHAR(2000),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_experiences_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_experience_employment_type
        CHECK (
            employment_type IN (
                'FULL_TIME',
                'PART_TIME',
                'INTERNSHIP',
                'CONTRACT',
                'FREELANCE'
            )
        ),

    CONSTRAINT chk_experience_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        ),

    CONSTRAINT chk_current_experience_end_date
        CHECK (
            currently_working = FALSE
            OR end_date IS NULL
        )
);

CREATE INDEX idx_user_experiences_user_id
    ON user_experiences(user_id);

CREATE INDEX idx_user_experiences_user_start_date
    ON user_experiences(user_id, start_date DESC);
