CREATE TABLE user_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    project_title VARCHAR(200) NOT NULL,
    description VARCHAR(3000),

    tech_stack VARCHAR(1000),

    github_url VARCHAR(500),
    live_url VARCHAR(500),

    start_date DATE,
    end_date DATE,

    currently_working BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_projects_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_project_dates
        CHECK (
            end_date IS NULL
            OR start_date IS NULL
            OR end_date >= start_date
        ),

    CONSTRAINT chk_current_project_end_date
        CHECK (
            currently_working = FALSE
            OR end_date IS NULL
        )
);

CREATE INDEX idx_user_projects_user_id
    ON user_projects(user_id);

CREATE INDEX idx_user_projects_user_start_date
    ON user_projects(user_id, start_date DESC);
