CREATE TABLE user_certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    certificate_name VARCHAR(200) NOT NULL,
    issuing_organization VARCHAR(200) NOT NULL,

    issue_date DATE,
    expiration_date DATE,

    does_not_expire BOOLEAN NOT NULL DEFAULT FALSE,

    credential_id VARCHAR(200),
    credential_url VARCHAR(500),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_certifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_certification_dates
        CHECK (
            expiration_date IS NULL
            OR issue_date IS NULL
            OR expiration_date >= issue_date
        ),

    CONSTRAINT chk_non_expiring_certificate
        CHECK (
            does_not_expire = FALSE
            OR expiration_date IS NULL
        )
);

CREATE INDEX idx_user_certifications_user_id
    ON user_certifications(user_id);

CREATE INDEX idx_user_certifications_issue_date
    ON user_certifications(user_id, issue_date DESC);
